version: "3"
silent: true

tasks:
  test:
    desc: Test the project
    cmds:
      - go test -cover ./...

  build:
    desc: Build the project
    cmds:
      - nix build

  lint:
    desc: Lint the project
    cmds:
      - golangci-lint run

  fmt:
    desc: Format the project
    cmds:
      - golangci-lint fmt
